$ErrorActionPreference = "Stop"

$ProjectRoot = "C:\iau-deeds-lands-platform"
$FilePath = Join-Path $ProjectRoot "src\app\components\ThemeInitializer.tsx"

if (-not (Test-Path -LiteralPath $FilePath)) {
    throw "ThemeInitializer.tsx was not found."
}

$Timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$BackupPath = "$FilePath.backup-$Timestamp"
Copy-Item -LiteralPath $FilePath -Destination $BackupPath -Force

$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$Content = [System.IO.File]::ReadAllText($FilePath, [System.Text.Encoding]::UTF8)

$ReplacementFunction = [System.Text.Encoding]::UTF8.GetString(
    [System.Convert]::FromBase64String("Y29uc3QgYXBwbHlGb250Q29udHJvbHMgPSAoCiAgc2V0dGluZ3M6IEZvbnRDb250cm9sU2V0dGluZ3MsCiAgYWxsb3dDb2xvck92ZXJyaWRlcyA9IHRydWUKKSA9PiB7CiAgY29uc3Qgcm9vdCA9IGRvY3VtZW50LmRvY3VtZW50RWxlbWVudDsKCiAgcm9vdC5zdHlsZS5zZXRQcm9wZXJ0eSgKICAgICctLWFwcC1mb250LWZhbWlseScsCiAgICBzZXR0aW5ncy5mb250RmFtaWx5IHx8ICdUYWphd2FsLCBDYWlybywgQXJpYWwsIHNhbnMtc2VyaWYnCiAgKTsKICByb290LnN0eWxlLnNldFByb3BlcnR5KAogICAgJy0tYXBwLWJhc2UtZm9udC1zaXplJywKICAgIHNldHRpbmdzLmJhc2VGb250U2l6ZSB8fCAnMTVweCcKICApOwogIHJvb3Quc3R5bGUuc2V0UHJvcGVydHkoCiAgICAnLS1hcHAtaGVhZGluZy1mb250LXdlaWdodCcsCiAgICBzZXR0aW5ncy5oZWFkaW5nRm9udFdlaWdodCB8fCAnODAwJwogICk7CgogIGlmIChhbGxvd0NvbG9yT3ZlcnJpZGVzKSB7CiAgICBjb25zdCBvcHRpb25hbENvbG9ycyA9IFsKICAgICAgWyctLWZvcmVncm91bmQnLCBzZXR0aW5ncy5mb3JlZ3JvdW5kXSwKICAgICAgWyctLW11dGVkLWZvcmVncm91bmQnLCBzZXR0aW5ncy5tdXRlZEZvcmVncm91bmRdLAogICAgICBbJy0tY2FyZC1mb3JlZ3JvdW5kJywgc2V0dGluZ3MuY2FyZEZvcmVncm91bmRdLAogICAgICBbJy0tc2lkZWJhci1mb3JlZ3JvdW5kJywgc2V0dGluZ3Muc2lkZWJhckZvcmVncm91bmRdLAogICAgICBbJy0tcHJpbWFyeScsIHNldHRpbmdzLnByaW1hcnldLAogICAgXSBhcyBjb25zdDsKCiAgICBvcHRpb25hbENvbG9ycy5mb3JFYWNoKChbdmFyaWFibGUsIGNvbG9yXSkgPT4gewogICAgICBpZiAoIWNvbG9yKSByZXR1cm47CiAgICAgIGNvbnN0IGhzbCA9IGhleFRvSHNsKGNvbG9yKTsKICAgICAgaWYgKGhzbCkgcm9vdC5zdHlsZS5zZXRQcm9wZXJ0eSh2YXJpYWJsZSwgaHNsKTsKICAgIH0pOwoKICAgIGlmIChzZXR0aW5ncy5zaWRlYmFyRm9yZWdyb3VuZCkgewogICAgICBjb25zdCBzaWRlYmFyID0gaGV4VG9Ic2woc2V0dGluZ3Muc2lkZWJhckZvcmVncm91bmQpOwogICAgICBpZiAoc2lkZWJhcikgewogICAgICAgIHJvb3Quc3R5bGUuc2V0UHJvcGVydHkoJy0tc2lkZWJhci1hY2NlbnQtZm9yZWdyb3VuZCcsIHNpZGViYXIpOwogICAgICB9CiAgICB9CgogICAgaWYgKHNldHRpbmdzLnByaW1hcnkpIHsKICAgICAgY29uc3QgcHJpbWFyeSA9IGhleFRvSHNsKHNldHRpbmdzLnByaW1hcnkpOwogICAgICBpZiAocHJpbWFyeSkgewogICAgICAgIHJvb3Quc3R5bGUuc2V0UHJvcGVydHkoJy0tcmluZycsIHByaW1hcnkpOwogICAgICAgIHJvb3Quc3R5bGUuc2V0UHJvcGVydHkoJy0tc2lkZWJhci1wcmltYXJ5JywgcHJpbWFyeSk7CiAgICAgIH0KICAgIH0KICB9Cn07")
)

$FunctionPattern = 'const applyFontControls = \(settings: FontControlSettings\) => \{.*?\r?\n\};\r?\n\r?\nconst injectAppearanceStyles'

if ($Content -match 'allowColorOverrides = true') {
    Write-Host "Font override guard already exists."
} else {
    $FunctionReplacement = $ReplacementFunction + [Environment]::NewLine + [Environment]::NewLine + 'const injectAppearanceStyles'
    $Updated = [System.Text.RegularExpressions.Regex]::Replace(
        $Content,
        $FunctionPattern,
        $FunctionReplacement,
        [System.Text.RegularExpressions.RegexOptions]::Singleline
    )

    if ($Updated -eq $Content) {
        throw "Could not patch applyFontControls."
    }

    $Content = $Updated
    Write-Host "Patched applyFontControls."
}

$OldCall = 'applyFontControls(JSON.parse(storedFont));'
$NewCall = @'
applyFontControls(
          JSON.parse(storedFont),
          normalizedTheme.mode !== 'dark'
        );
'@

if ($Content.Contains($OldCall)) {
    $Content = $Content.Replace($OldCall, $NewCall.TrimEnd())
    Write-Host "Patched stored font settings."
} elseif ($Content -match "normalizedTheme\.mode !== 'dark'") {
    Write-Host "Stored font settings are already patched."
} else {
    throw "Could not patch the stored font call."
}

$CssBlock = [System.Text.Encoding]::UTF8.GetString(
    [System.Convert]::FromBase64String("CiAgICAvKiBGSU5BTF9EQVJLX1JFQURBQklMSVRZX0ZJWCAqLwogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIHsKICAgICAgY29sb3Itc2NoZW1lOiBkYXJrOwogICAgfQoKICAgIGh0bWxbZGF0YS1hcHBlYXJhbmNlLW1vZGU9ImRhcmsiXSBib2R5LAogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIG1haW4gewogICAgICBjb2xvcjogaHNsKHZhcigtLWZvcmVncm91bmQpKSAhaW1wb3J0YW50OwogICAgfQoKICAgIGh0bWxbZGF0YS1hcHBlYXJhbmNlLW1vZGU9ImRhcmsiXSBtYWluIHsKICAgICAgYmFja2dyb3VuZDoKICAgICAgICByYWRpYWwtZ3JhZGllbnQoY2lyY2xlIGF0IDEyJSA4JSwgdmFyKC0tYXBwZWFyYW5jZS1nbG93KSwgdHJhbnNwYXJlbnQgMzAlKSwKICAgICAgICByYWRpYWwtZ3JhZGllbnQoY2lyY2xlIGF0IDg4JSAxNSUsIHZhcigtLWFwcGVhcmFuY2UtZ2xvdy1zZWNvbmRhcnkpLCB0cmFuc3BhcmVudCAzMCUpLAogICAgICAgIGhzbCh2YXIoLS1iYWNrZ3JvdW5kKSAvIC44OCkgIWltcG9ydGFudDsKICAgIH0KCiAgICBodG1sW2RhdGEtYXBwZWFyYW5jZS1tb2RlPSJkYXJrIl0gbWFpbiBbY2xhc3MqPSJiZy13aGl0ZSJdLAogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIG1haW4gW2NsYXNzKj0iYmctc2xhdGUtNTAiXSwKICAgIGh0bWxbZGF0YS1hcHBlYXJhbmNlLW1vZGU9ImRhcmsiXSBtYWluIFtjbGFzcyo9ImJnLWdyYXktNTAiXSwKICAgIGh0bWxbZGF0YS1hcHBlYXJhbmNlLW1vZGU9ImRhcmsiXSBtYWluIFtjbGFzcyo9ImJnLXNreS01MCJdLAogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIG1haW4gW2NsYXNzKj0iYmctYmx1ZS01MCJdLAogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIG1haW4gW2NsYXNzKj0iYmctdmlvbGV0LTUwIl0gewogICAgICBjb2xvcjogaHNsKHZhcigtLWNhcmQtZm9yZWdyb3VuZCkpICFpbXBvcnRhbnQ7CiAgICAgIGJhY2tncm91bmQtY29sb3I6IHZhcigtLWFwcGVhcmFuY2UtZ2xhc3Mtc3Ryb25nKSAhaW1wb3J0YW50OwogICAgICBib3JkZXItY29sb3I6IHZhcigtLWFwcGVhcmFuY2UtZ2xhc3MtYm9yZGVyKSAhaW1wb3J0YW50OwogICAgfQoKICAgIGh0bWxbZGF0YS1hcHBlYXJhbmNlLW1vZGU9ImRhcmsiXSBtYWluIFtjbGFzcyo9ImZyb20td2hpdGUiXSwKICAgIGh0bWxbZGF0YS1hcHBlYXJhbmNlLW1vZGU9ImRhcmsiXSBtYWluIFtjbGFzcyo9InZpYS13aGl0ZSJdLAogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIG1haW4gW2NsYXNzKj0idG8td2hpdGUiXSwKICAgIGh0bWxbZGF0YS1hcHBlYXJhbmNlLW1vZGU9ImRhcmsiXSBtYWluIFtjbGFzcyo9ImZyb20tc2t5LTUwIl0sCiAgICBodG1sW2RhdGEtYXBwZWFyYW5jZS1tb2RlPSJkYXJrIl0gbWFpbiBbY2xhc3MqPSJ2aWEtc2t5LTUwIl0sCiAgICBodG1sW2RhdGEtYXBwZWFyYW5jZS1tb2RlPSJkYXJrIl0gbWFpbiBbY2xhc3MqPSJ0by1za3ktNTAiXSwKICAgIGh0bWxbZGF0YS1hcHBlYXJhbmNlLW1vZGU9ImRhcmsiXSBtYWluIFtjbGFzcyo9ImZyb20tYmx1ZS01MCJdLAogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIG1haW4gW2NsYXNzKj0idG8tYmx1ZS01MCJdLAogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIG1haW4gW2NsYXNzKj0iZnJvbS12aW9sZXQtNTAiXSwKICAgIGh0bWxbZGF0YS1hcHBlYXJhbmNlLW1vZGU9ImRhcmsiXSBtYWluIFtjbGFzcyo9InRvLXZpb2xldC01MCJdIHsKICAgICAgY29sb3I6IGhzbCh2YXIoLS1jYXJkLWZvcmVncm91bmQpKSAhaW1wb3J0YW50OwogICAgICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1hcHBlYXJhbmNlLWdsYXNzLXN0cm9uZykgIWltcG9ydGFudDsKICAgICAgYmFja2dyb3VuZC1pbWFnZToKICAgICAgICByYWRpYWwtZ3JhZGllbnQoY2lyY2xlIGF0IDE0JSA4JSwgdmFyKC0tYXBwZWFyYW5jZS1nbG93KSwgdHJhbnNwYXJlbnQgMjglKSwKICAgICAgICByYWRpYWwtZ3JhZGllbnQoY2lyY2xlIGF0IDg4JSAxNiUsIHZhcigtLWFwcGVhcmFuY2UtZ2xvdy1zZWNvbmRhcnkpLCB0cmFuc3BhcmVudCAyOCUpLAogICAgICAgIGxpbmVhci1ncmFkaWVudCgKICAgICAgICAgIDEzNWRlZywKICAgICAgICAgIHZhcigtLWFwcGVhcmFuY2UtZ2xhc3Mtc3Ryb25nKSwKICAgICAgICAgIHZhcigtLWFwcGVhcmFuY2UtZ2xhc3MpCiAgICAgICAgKSAhaW1wb3J0YW50OwogICAgICBib3JkZXItY29sb3I6IHZhcigtLWFwcGVhcmFuY2UtZ2xhc3MtYm9yZGVyKSAhaW1wb3J0YW50OwogICAgICBib3gtc2hhZG93OgogICAgICAgIHZhcigtLWFwcGVhcmFuY2UtY2FyZC1zaGFkb3cpLAogICAgICAgIGluc2V0IDAgMXB4IDAgcmdiYSgyNTUsMjU1LDI1NSwuMDgpICFpbXBvcnRhbnQ7CiAgICB9CgogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIG1haW4gLnRleHQtc2xhdGUtOTUwLAogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIG1haW4gLnRleHQtc2xhdGUtOTAwLAogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIG1haW4gLnRleHQtc2xhdGUtODAwLAogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIG1haW4gLnRleHQtc2xhdGUtNzAwLAogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIG1haW4gLnRleHQtZ3JheS05NTAsCiAgICBodG1sW2RhdGEtYXBwZWFyYW5jZS1tb2RlPSJkYXJrIl0gbWFpbiAudGV4dC1ncmF5LTkwMCwKICAgIGh0bWxbZGF0YS1hcHBlYXJhbmNlLW1vZGU9ImRhcmsiXSBtYWluIC50ZXh0LWdyYXktODAwLAogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIG1haW4gLnRleHQtZ3JheS03MDAgewogICAgICBjb2xvcjogaHNsKHZhcigtLWZvcmVncm91bmQpKSAhaW1wb3J0YW50OwogICAgfQoKICAgIGh0bWxbZGF0YS1hcHBlYXJhbmNlLW1vZGU9ImRhcmsiXSBtYWluIC50ZXh0LXNsYXRlLTYwMCwKICAgIGh0bWxbZGF0YS1hcHBlYXJhbmNlLW1vZGU9ImRhcmsiXSBtYWluIC50ZXh0LXNsYXRlLTUwMCwKICAgIGh0bWxbZGF0YS1hcHBlYXJhbmNlLW1vZGU9ImRhcmsiXSBtYWluIC50ZXh0LWdyYXktNjAwLAogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIG1haW4gLnRleHQtZ3JheS01MDAsCiAgICBodG1sW2RhdGEtYXBwZWFyYW5jZS1tb2RlPSJkYXJrIl0gbWFpbiAudGV4dC1tdXRlZC1mb3JlZ3JvdW5kIHsKICAgICAgY29sb3I6IGhzbCh2YXIoLS1tdXRlZC1mb3JlZ3JvdW5kKSkgIWltcG9ydGFudDsKICAgIH0KCiAgICBodG1sW2RhdGEtYXBwZWFyYW5jZS1tb2RlPSJkYXJrIl0gbWFpbiBpbnB1dCwKICAgIGh0bWxbZGF0YS1hcHBlYXJhbmNlLW1vZGU9ImRhcmsiXSBtYWluIHRleHRhcmVhLAogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIG1haW4gc2VsZWN0LAogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIG1haW4gW3JvbGU9ImNvbWJvYm94Il0gewogICAgICBjb2xvcjogaHNsKHZhcigtLWZvcmVncm91bmQpKSAhaW1wb3J0YW50OwogICAgICBiYWNrZ3JvdW5kLWNvbG9yOiBoc2wodmFyKC0taW5wdXQpIC8gLjk0KSAhaW1wb3J0YW50OwogICAgICBib3JkZXItY29sb3I6IHZhcigtLWFwcGVhcmFuY2UtZ2xhc3MtYm9yZGVyKSAhaW1wb3J0YW50OwogICAgICBjYXJldC1jb2xvcjogaHNsKHZhcigtLXByaW1hcnkpKSAhaW1wb3J0YW50OwogICAgfQoKICAgIGh0bWxbZGF0YS1hcHBlYXJhbmNlLW1vZGU9ImRhcmsiXSBtYWluIGlucHV0OjpwbGFjZWhvbGRlciwKICAgIGh0bWxbZGF0YS1hcHBlYXJhbmNlLW1vZGU9ImRhcmsiXSBtYWluIHRleHRhcmVhOjpwbGFjZWhvbGRlciB7CiAgICAgIGNvbG9yOiBoc2wodmFyKC0tbXV0ZWQtZm9yZWdyb3VuZCkpICFpbXBvcnRhbnQ7CiAgICAgIG9wYWNpdHk6IC45NiAhaW1wb3J0YW50OwogICAgfQoKICAgIGh0bWxbZGF0YS1hcHBlYXJhbmNlLW1vZGU9ImRhcmsiXSBtYWluIHNlbGVjdCBvcHRpb24gewogICAgICBjb2xvcjogaHNsKHZhcigtLWZvcmVncm91bmQpKSAhaW1wb3J0YW50OwogICAgICBiYWNrZ3JvdW5kOiBoc2wodmFyKC0tcG9wb3ZlcikpICFpbXBvcnRhbnQ7CiAgICB9CgogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIG1haW4gdGFibGUsCiAgICBodG1sW2RhdGEtYXBwZWFyYW5jZS1tb2RlPSJkYXJrIl0gbWFpbiB0aGVhZCwKICAgIGh0bWxbZGF0YS1hcHBlYXJhbmNlLW1vZGU9ImRhcmsiXSBtYWluIHRib2R5LAogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIG1haW4gdHIsCiAgICBodG1sW2RhdGEtYXBwZWFyYW5jZS1tb2RlPSJkYXJrIl0gbWFpbiB0aCwKICAgIGh0bWxbZGF0YS1hcHBlYXJhbmNlLW1vZGU9ImRhcmsiXSBtYWluIHRkIHsKICAgICAgYmFja2dyb3VuZC1jb2xvcjogdHJhbnNwYXJlbnQgIWltcG9ydGFudDsKICAgICAgYm9yZGVyLWNvbG9yOiB2YXIoLS1hcHBlYXJhbmNlLWdsYXNzLWJvcmRlcikgIWltcG9ydGFudDsKICAgIH0KCiAgICBodG1sW2RhdGEtYXBwZWFyYW5jZS1tb2RlPSJkYXJrIl0gbWFpbiB0aCB7CiAgICAgIGNvbG9yOiBoc2wodmFyKC0tZm9yZWdyb3VuZCkpICFpbXBvcnRhbnQ7CiAgICAgIGZvbnQtd2VpZ2h0OiA3NTAgIWltcG9ydGFudDsKICAgIH0KCiAgICBodG1sW2RhdGEtYXBwZWFyYW5jZS1tb2RlPSJkYXJrIl0gbWFpbiB0ZCB7CiAgICAgIGNvbG9yOiBoc2wodmFyKC0tY2FyZC1mb3JlZ3JvdW5kKSkgIWltcG9ydGFudDsKICAgIH0KCiAgICBodG1sW2RhdGEtYXBwZWFyYW5jZS1tb2RlPSJkYXJrIl0gbWFpbiB0Ym9keSB0cjpob3ZlciB7CiAgICAgIGJhY2tncm91bmQtY29sb3I6IGhzbCh2YXIoLS1tdXRlZCkgLyAuNjIpICFpbXBvcnRhbnQ7CiAgICB9CgogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIG1haW4gYnV0dG9uW2NsYXNzKj0iYmctcHJpbWFyeSJdLAogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtbW9kZT0iZGFyayJdIG1haW4gYnV0dG9uW2NsYXNzKj0iZnJvbS1za3ktNjAwIl0sCiAgICBodG1sW2RhdGEtYXBwZWFyYW5jZS1tb2RlPSJkYXJrIl0gbWFpbiBidXR0b25bY2xhc3MqPSJmcm9tLWJsdWUtNjAwIl0sCiAgICBodG1sW2RhdGEtYXBwZWFyYW5jZS1tb2RlPSJkYXJrIl0gbWFpbiBhW2NsYXNzKj0iYmctcHJpbWFyeSJdIHsKICAgICAgY29sb3I6IGhzbCh2YXIoLS1wcmltYXJ5LWZvcmVncm91bmQpKSAhaW1wb3J0YW50OwogICAgfQoKICAgIGh0bWxbZGF0YS1hcHBlYXJhbmNlLXRoZW1lPSJmdXR1cmUtbmVvbi1kYXJrIl0gewogICAgICAtLWZvcmVncm91bmQ6IDIxMCAxMDAlIDk4JTsKICAgICAgLS1jYXJkLWZvcmVncm91bmQ6IDIxMCAxMDAlIDk4JTsKICAgICAgLS1tdXRlZC1mb3JlZ3JvdW5kOiAyMTUgNDIlIDgyJTsKICAgICAgLS1wb3BvdmVyLWZvcmVncm91bmQ6IDIxMCAxMDAlIDk4JTsKICAgICAgLS1zaWRlYmFyLWZvcmVncm91bmQ6IDIxMCAxMDAlIDk3JTsKICAgICAgLS1zaWRlYmFyLWFjY2VudC1mb3JlZ3JvdW5kOiAyMTAgMTAwJSA5OCU7CiAgICB9CgogICAgaHRtbFtkYXRhLWFwcGVhcmFuY2UtdGhlbWU9InNpbHZlci1ub2lyIl0gewogICAgICAtLWZvcmVncm91bmQ6IDIxNCA1NSUgOTglOwogICAgICAtLWNhcmQtZm9yZWdyb3VuZDogMjE0IDU1JSA5OCU7CiAgICAgIC0tbXV0ZWQtZm9yZWdyb3VuZDogMjE1IDMyJSA4MCU7CiAgICAgIC0tcG9wb3Zlci1mb3JlZ3JvdW5kOiAyMTQgNTUlIDk4JTsKICAgICAgLS1zaWRlYmFyLWZvcmVncm91bmQ6IDIxNCA1NSUgOTclOwogICAgICAtLXNpZGViYXItYWNjZW50LWZvcmVncm91bmQ6IDIxNCA1NSUgOTglOwogICAgfQo=")
)

if ($Content.Contains("FINAL_DARK_READABILITY_FIX")) {
    Write-Host "Final CSS layer already exists."
} else {
    $Marker = "    @media (max-width: 1279px) {"

    if (-not $Content.Contains($Marker)) {
        throw "Could not find the CSS insertion marker."
    }

    $Content = $Content.Replace(
        $Marker,
        $CssBlock + [Environment]::NewLine + [Environment]::NewLine + $Marker
    )

    Write-Host "Added final dark readability CSS."
}

[System.IO.File]::WriteAllText($FilePath, $Content, $Utf8NoBom)

Write-Host ""
Write-Host "DONE: dark theme readability fix applied."
Write-Host "Backup: $BackupPath"
Write-Host "Next: npm.cmd run build"
