from pathlib import Path


def replace_once(path, old, new):
    p = Path(path)
    text = p.read_text(encoding='utf-8')
    if old not in text:
        raise SystemExit(f'Expected block not found in {path}: {old[:140]!r}')
    p.write_text(text.replace(old, new, 1), encoding='utf-8')


records = 'src/app/pages/AccountingTransformationRecordsPage.tsx'
replace_once(records, """}> = ({ item, canEdit, canDelete, onView, onEdit, onDelete }) => {\n  const { Icon, tone } = typeVisual(item.recordType);\n  return (\n""", """}> = ({ item, canEdit, canDelete, onView, onEdit, onDelete }) => {\n  const { Icon, tone } = typeVisual(item.recordType);\n  const isLand = item.recordType === 'land';\n  const landDeedNumber = isLand ? String(item.payload?.AJ ?? '').trim() : '';\n  const landDeedDate = isLand ? String(item.payload?.AG ?? '').trim() : '';\n  return (\n""")

replace_once(records, """          <div className=\"rounded-xl border bg-white/70 p-3\"><span className=\"text-slate-500\">رقم الأصل بالجهة</span><p className=\"mt-1 truncate font-bold text-slate-800\">{item.entityAssetNumber || '-'}</p></div>\n          <div className=\"rounded-xl border bg-white/70 p-3\"><span className=\"text-slate-500\">المدينة</span><p className=\"mt-1 truncate font-bold text-slate-800\">{item.city || '-'}</p></div>\n          <div className=\"rounded-xl border bg-white/70 p-3\"><span className=\"text-slate-500\">رمز الأصل المحاسبي</span><p className=\"mt-1 truncate font-bold text-slate-800\">{item.accountingAssetCode || '-'}</p></div>\n""", """          <div className=\"rounded-xl border bg-white/70 p-3\"><span className=\"text-slate-500\">{isLand ? 'رقم الصك — AJ' : 'رقم الأصل بالجهة'}</span><p className=\"mt-1 truncate font-bold text-slate-800\">{isLand ? (landDeedNumber || '-') : (item.entityAssetNumber || '-')}</p></div>\n          <div className=\"rounded-xl border bg-white/70 p-3\"><span className=\"text-slate-500\">{isLand ? 'تاريخ الصك — AG' : 'المدينة'}</span><p className=\"mt-1 truncate font-bold text-slate-800\">{isLand ? (landDeedDate || '-') : (item.city || '-')}</p></div>\n          <div className=\"rounded-xl border bg-white/70 p-3\"><span className=\"text-slate-500\">رمز الأصل المحاسبي</span><p className=\"mt-1 truncate font-bold text-slate-800\">{item.accountingAssetCode || '-'}</p></div>\n""")

responsive = 'src/app/pages/AccountingTransformationResponsiveImportPage.tsx'
replace_once(responsive, """const sourceBadge = (item: PreviewItem) => item.recordType === 'fixed_asset'\n  ? { label: `مخطط نموذج ب ${MODEL_B_VERSION}`, className: 'border-violet-300 bg-violet-50 text-violet-800' }\n  : { label: 'مصدر Legacy مرتبط بنيويًا', className: 'border-sky-300 bg-sky-50 text-sky-800' };\n""", """const sourceBadge = (item: PreviewItem) => item.recordType === 'fixed_asset'\n  ? { label: `مخطط نموذج ب ${MODEL_B_VERSION}`, className: 'border-violet-300 bg-violet-50 text-violet-800' }\n  : item.recordType === 'land'\n    ? { label: 'هوية الأرض: رقم الصك AJ + تاريخ الصك AG', className: 'border-amber-300 bg-amber-50 text-amber-900' }\n    : { label: 'مصدر Legacy مرتبط بنيويًا', className: 'border-sky-300 bg-sky-50 text-sky-800' };\n""")

replace_once(responsive, """<table className=\"w-full min-w-[1100px] text-xs\"><thead className=\"bg-slate-50\"><tr><th className=\"p-3 text-right\">الحالة</th><th className=\"p-3 text-right\">المصدر</th><th className=\"p-3 text-right\">النوع</th><th className=\"p-3 text-right\">صف Excel</th><th className=\"p-3 text-right\">رقم الأصل</th><th className=\"p-3 text-right\">وصف الأصل</th><th className=\"p-3 text-right\">طريقة الربط</th></tr></thead><tbody>""", """<table className=\"w-full min-w-[1250px] text-xs\"><thead className=\"bg-slate-50\"><tr><th className=\"p-3 text-right\">الحالة</th><th className=\"p-3 text-right\">المصدر</th><th className=\"p-3 text-right\">النوع</th><th className=\"p-3 text-right\">صف Excel</th><th className=\"p-3 text-right\">رقم الصك / الأصل</th><th className=\"p-3 text-right\">تاريخ الصك</th><th className=\"p-3 text-right\">وصف الأصل</th><th className=\"p-3 text-right\">طريقة الربط</th></tr></thead><tbody>""")

replace_once(responsive, """            const number = item.recordType === 'fixed_asset' ? String(item.payload.Y || item.payload.Z || item.payload.AB || '-') : String(item.payload.E || item.payload.D || '-');\n            const description = item.recordType === 'fixed_asset' ? String(item.payload.AA || '-') : String(item.payload.G || '-');\n            return <tr key={`${item.sourceSheet}-${item.sourceRow}-${globalIndex}`} className=\"border-t\"><td className=\"p-3\"><Badge variant=\"outline\" className={status.className}>{status.label}</Badge></td><td className=\"p-3 font-bold\">{item.sourceSheet}</td><td className=\"p-3\">{recordTypeLabel(item.recordType)}</td><td className=\"p-3\">{item.sourceRow}</td><td className=\"p-3\">{number}</td><td className=\"max-w-[320px] truncate p-3\">{description}</td><td className=\"p-3\"><Badge variant=\"outline\" className={source.className}>{source.label}</Badge></td></tr>;\n""", """            const number = item.recordType === 'fixed_asset'\n              ? String(item.payload.Y || item.payload.Z || item.payload.AB || '-')\n              : item.recordType === 'land'\n                ? String(item.payload.AJ || '-')\n                : String(item.payload.E || item.payload.D || '-');\n            const deedDate = item.recordType === 'land' ? String(item.payload.AG || '-') : '-';\n            const description = item.recordType === 'fixed_asset' ? String(item.payload.AA || '-') : String(item.payload.G || '-');\n            return <tr key={`${item.sourceSheet}-${item.sourceRow}-${globalIndex}`} className=\"border-t\"><td className=\"p-3\"><Badge variant=\"outline\" className={status.className}>{status.label}</Badge></td><td className=\"p-3 font-bold\">{item.sourceSheet}</td><td className=\"p-3\">{recordTypeLabel(item.recordType)}</td><td className=\"p-3\">{item.sourceRow}</td><td className=\"p-3 font-bold\">{number}</td><td className=\"p-3\">{deedDate}</td><td className=\"max-w-[320px] truncate p-3\">{description}</td><td className=\"p-3\"><Badge variant=\"outline\" className={source.className}>{source.label}</Badge></td></tr>;\n""")

print('Applied AJ/AG land deed display changes.')
